### ISSUE TITLE
Page contact - bloc activités

### ISSUE THREAD

**Issue by romainpolytech** [ebiolevitch/DUTIL_FORCONT#2]
![contact](https://cloud.githubusercontent.com/assets/11872494/7536227/4f33b5d0-f58e-11e4-8437-d416ffabeb82.png)

sur la page des contacts, le rendu du bloc Activités n'est pas beau. Pb de CSS ?

**Comment by ebiolevitch** [comment]
Ok pour la css. Commit à faire demain (premier commit sur des fichiers modifiés de chaque côté, je préférerais que l'on se fasse une copie de sauvegarde de nos fichiers perso avant!).
