### ISSUE TITLE
Encadré contact

### ISSUE THREAD

**Issue by romainpolytech** [ebiolevitch/DUTIL_FORCONT#5]
je ne parviens pas à supprimer l'encadré de cotnact sur la apge de la structure "Service formation continue de Polytech Nantes", qui s'affiche lorsqu'on clique sur "Tous les contacts du Service Formation Continue de Polytech Nantes"
Il faudrait que l'encadré ne soit pas visible sur cette page.

**Comment by ebiolevitch** [comment]
Pas possible de l'enlever avec ce type de fiche, car elle s'insère dans la rubrique courante ( qui contient cet encadré).

**Comment by romainpolytech** [comment]
C'est ce que je me disais. Du coup au lieu de mettre l'encadré à la base et
dupliqué par défaut, on le mettra à chaque rubrique voire page, pour
pouvoir ne pas le mettre quand on le veut

Romain
