### ISSUE TITLE
Fil d'ariane Notre offre

### ISSUE THREAD

**Issue by romainpolytech** [ebiolevitch/DUTIL_FORCONT#7]
Sur la partie Notre offre, le fil d'ariane reste sur "Accueil"

![capture du 2015-05-13 16 28 33](https://cloud.githubusercontent.com/assets/11872494/7612801/3d7c0952-f98d-11e4-8ab9-a8878a4f521d.png)

**Comment by ebiolevitch** [comment]
Corrections apportées dans le paramétrage des rubriques (Catégorie = indéfini(e)).
