### ISSUE TITLE
Mise en forme du résultat de la recherche

### ISSUE THREAD

**Issue by ebiolevitch** [ebiolevitch/DUTIL_FORCONT#8]
La mise en forme du résultat de la recherche d'une formation est incorrecte.
Revoir la css associée.

**Comment by romainpolytech** [comment]
qu'est ce qui ne va pas ?

Romain

2015-05-14 1:00 GMT+02:00 ebiolevitch notifications@github.com:

**Comment by ebiolevitch** [comment]
Sur mon poste, les puces et le texte se chevauchent. Je n'ai pas encore analysé (pb css, pb navigateur...)

**Comment by romainpolytech** [comment]
ok, sur le mien c'est correct..???

Romain

2015-05-14 11:33 GMT+02:00 ebiolevitch notifications@github.com:

**Comment by romainpolytech** [comment]
j'avais enf ait le même problème. Css modifiée, commit effectué. Dis moi si c'est bon pour toi
